name: Findit CI

on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses:
        with:
          node-version: 14
      - run: npm ci
      - nun: npm test
      - run: npm run build
